name: Build, Test, and Deploy the Application

on: [push]

jobs:  
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: "docker/whalesay"
    steps:
    - name: Build and Test
      run: cowsay This is the Build and Test step
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: "docker/whalesay"
    steps:
    - name: Deploying the application
      run: cowsay This is the Deploy step
